"""rename address

Revision ID: 365de1541610
Revises: 5b5b8c802e04
Create Date: 2025-04-06 12:23:08.982148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365de1541610'
down_revision = '5b5b8c802e04'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###